name: Coverage

on:
  workflow_call:
    inputs:
      use_ct_registry:
        required: false
        default: false
        type: boolean
    secrets:
      codecov-secret:
        description: 'Codecov token for repository'
        required: false
      SSH_KEY:
        required: false

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Julia
        id: julia
        uses: julia-actions/setup-julia@latest

      # Add ct-registry (only if use_registry is true and SSH_KEY is provided)
      - name: Add ct-registry
        if: inputs.use_ct_registry
        uses: julia-actions/add-julia-registry@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          registry: control-toolbox/ct-registry

      # 🧰 Cache des artefacts Julia (binaries téléchargés)
      - name: Cache Julia artifacts
        uses: actions/cache@v5
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-${{ steps.julia.outputs.julia-version }}-artifacts-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-${{ steps.julia.outputs.julia-version }}-artifacts-

      # ⚡ Cache du code précompilé (.ji)
      - name: Cache Julia compiled code
        uses: actions/cache@v5
        with:
          path: ~/.julia/compiled
          key: ${{ runner.os }}-julia-${{ steps.julia.outputs.julia-version }}-compiled-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-${{ steps.julia.outputs.julia-version }}-compiled-

      # 🧱 Exécuter les tests
      - uses: julia-actions/julia-runtest@latest

      # 📊 Générer les fichiers de couverture
      - uses: julia-actions/julia-processcoverage@latest

      # ☁️ Envoyer les résultats à Codecov
      - uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.codecov-secret }}
