name: Remove Julia Installation

on:
  workflow_dispatch:
  schedule:
    - cron: 12 3 * * 1
  
jobs:
  Clean:
    runs-on: self-hosted
    steps:
      - name: "Remove Julia installation"
        run: /usr/bin/rm -fr /builds/actions-runner/_work/_tool/julia /builds/.julia || /usr/bin/true
        shell: bash
